version: '3'
services:
  ml:
    image: mlapi
    volumes:
      - ./src:/app
      - ./model:/model
      - ./training_data:/training_data
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    ports:
      - 8000:8888
