version: '3'
services:
  dash:
      image: dashapp
      ports:
          - 8888:8888
      links:
          - mlapi
      volumes:
          - ./dash/src:/src
          - ./data:/data

  mlapi:
      image: mlapi
      expose:
          - 8000
      volumes:
          - ./ml/src:/src
          - ./ml/model:/model
          - ./data:/data
