version: '3'
services:
  dash:
      image: dashapp
      ports:
        - 8888:8888
      volumes:
        - ./dash/app:/app
        - ./data:/data
  mlapi:
      image: mlapi
      expose:
        - 8000
      ports:
        - 8000:8000
      volumes:
        - ./mlapi/src:/app
        - ./mlapi/model:/model
        - ./data:/data
